

version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=familianetdb
    ports:
      - 3307:3306

  app:
    image: app:latest
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/familianetdb?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    depends_on:
      - mysql